# Generated by Django 2.2.1 on 2019-05-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ffffActor',
        ),
        migrations.AddField(
            model_name='movie',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
