# Generated by Django 2.2.1 on 2019-05-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_auto_20190526_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='show_type',
            field=models.CharField(default='Movie', max_length=100),
        ),
    ]
