# Generated by Django 2.2.1 on 2019-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0003_movie_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors_string',
            field=models.TextField(default=''),
        ),
    ]
